version: '3'

services:
    frontend:
        build: 
            context: .
        volumes: 
            - ${PWD}:/app
            - /app/node_modules
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USERPOOLING=true
networks:
    default:
        external:
            name: easydoc
