version: '3'

services:
    backend:
        build:
            context: backend
        environment:
            - BACKEND_ROOT=${PWD}/backend
        volumes:
            - ${PWD}/backend:/app
            - /root/.ssh:/root/.ssh
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 5000:5000

    frontend:
        build: 
            context: frontend
        volumes: 
            - ${PWD}/frontend/src:/app/src
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USERPOOLING=true
            - NODE_OPTIONS=--max_old_space_size=4096

