version: '3'

services:
    backend:
        build:
            context: .
        volumes:
            - ${PWD}:/app
            - ${HOME}/.ssh:/root/.ssh
        ports:
            - 5000:5000
networks:
    default:
        external:
            name: easydoc
